/**:
  ros__parameters:
    common:
      on_time_buffer: 0.3
      off_time_buffer: 0.3
      range:
        forward: 10.0
        backward: 100.0
      predicted_path:
        # predicted path parameters
        min_velocity: 1.38                              # [m/s]
        max_velocity: 50.0                              # [m/s]
        acceleration: 1.50
        time_resolution: 0.5                            # [s]
        time_horizon: 3.0
        delay_until_departure: 0.0                      # [s]
      rss:
        # rss parameters
        extended_polygon_policy: rectangle             # [-] select "rectangle" or "along_path"
        vehicle_deceleration: -2.0               # [m/ss]
        vehicle_reaction_time: 2.0                 # [s]
        vehicle_safety_time_margin: 1.0            # [s]
        lateral_distance_max_threshold: 1.0             # [m]
        longitudinal_distance_min_threshold: 3.0        # [m]
        longitudinal_velocity_delta_time: 0.0           # [s]

    static_obstacle_avoidance:
      topic: /planning/planning_factors/static_obstacle_avoidance
      behavior: [shift_left, shift_right]
      safety_condition: safe
      target_type: [bus, car, motorcycle, trailer, truck]
      current_lane: false
      adjacent_lane: true

    lane_change_left:
      topic: /planning/planning_factors/lane_change_left
      behavior: [shift_left]
      safety_condition: safe
      target_type: [bus, car, motorcycle, trailer, truck]
      current_lane: false
      adjacent_lane: true

    lane_change_right:
      topic: /planning/planning_factors/lane_change_right
      behavior: [shift_right]
      safety_condition: safe
      target_type: [bus, car, motorcycle, trailer, truck]
      current_lane: false
      adjacent_lane: true

    pull_out:
      topic: /planning/planning_factors/start_planner
      behavior: [shift_left, shift_right]
      safety_condition: safe
      target_type: [bus, car, motorcycle, trailer, truck]
      current_lane: false
      adjacent_lane: true

    pull_over:
      topic: /planning/planning_factors/goal_planner
      behavior: [shift_left, shift_right]
      safety_condition: safe
      target_type: [bus, car, motorcycle, trailer, truck]
      current_lane: false
      adjacent_lane: true

    behavior_path_planner:
      topic: /planning/planning_factors/behavior_path_planner
      behavior: [turn_left, turn_right]
      safety_condition: both
      target_type: [bicycle, motorcycle, pedestrian]
      current_lane: true
      adjacent_lane: false
